-- AlterTable
ALTER TABLE "ClassDate" ALTER COLUMN "date" SET DATA TYPE DATE;

-- AlterTable
ALTER TABLE "Student" ALTER COLUMN "birth_date" SET DATA TYPE DATE,
ALTER COLUMN "cna_exp_date" SET DATA TYPE DATE,
ALTER COLUMN "chha_exp_date" SET DATA TYPE DATE;
